### PR TITLE
Remove custom submodules in docs

### PR DESCRIPTION
**Pull request by emlaver**
## PR summary

Fixes: #49

**Note: An existing issue is [required](https://github.com/IBM/cloudant-python-sdk/blob/master/CONTRIBUTING.md#PRs) before opening a PR.**

## PR Checklist

Please make sure that your PR fulfills the following requirements:

- [ ] The commit message follows the
[Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [x] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?
Custom `common`, `version`, and `cloudant_base_service` exist in the documentation.  The user does not need to interact with these modules and they can be excluded in the docs.  

## What is the new behavior?
Custom modules `common`, `version`, and `cloudant_base_service` removed in docs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by emlaver** [comment]
This is what `apidocs/modules.html` looks like locally:
Screen Shot 2021-10-21 at 11 22 51 PM

**Review by mojito317 — COMMENTED** [review]
Wdyt about `couchdb_session_get_authenticator_patch`? Users should not interact with that too, right?

**Comment by emlaver** [comment]
> Wdyt about `couchdb_session_get_authenticator_patch`? Users should not interact with that too, right?

Yes you're right, I'll remove that too.

**Review by mojito317 — APPROVED** [review]
lgtm!

**Pull request merged**
